### ISSUE TITLE
source

### ISSUE THREAD

**Issue by bkyerv** [payloadcms/website-cms#17]
On the website there is a link that when clicked leads to this repo saying that the repo includes source code of the website
![image](https://user-images.githubusercontent.com/87478959/203462310-55e9a6e1-158d-45bf-8297-7017100af8f9.png)

When I opened server.ts file in this repo it seems that any request to the root domain should result in redirect to admin pathname 

`app.get('/', (_, res) => {
  res.redirect('/admin');
});`

However when I request https://payloadcms.com no redirect is happenning. Does that mean that source code in the repo is not source code of the website but source code of the backen(server) that the website relies upon? When I clicked the button on the website promising to show the source code of the website I was expecting to see frontend code for the client but seems like I am looking at the backend code

**Comment by jmikrut** [comment]
Hey @bkyerv — there are two repos. This one is the CMS that powers the website, but the Next frontend is also available and is linked to from the readme. It's here:

https://github.com/payloadcms/website
