### ISSUE TITLE
QUESTION: Plans for migration to payload 2.0

### ISSUE THREAD

**Issue by AlexJeffcott** [payloadcms/website-cms#46]
I was just wondering what the plans for migrating this project to payload 2.0 (and possibly lexical and vite), as I imagine that this is what many would like to do, if they are using this as a template.

**Comment by jmikrut** [comment]
Hey @AlexJeffcott — we are actually building a fully new site that will be on Payload 2.0 with Lexical!

More from us on this soon. But that's why we haven't rushed to update this one yet. It's going to be completely updated, hopefully within the next few months. 👍

**Comment by AlexJeffcott** [comment]
Ah, wonderful, thanks for letting me know @jmikrut.

In the meantime, I am keen to play around with v2, vite, postgres and lexical.

Is there somewhere I can draw on to see a lexical rich text implementation with payload 2.0?
